"""Emit one explicit M1 walking-bicycle sphere-probe contract for GIS and C++."""
import json
import math
from pathlib import Path
from acquire_sources import digest, save_json

ROOT = Path(__file__).resolve().parents[2]


def main():
    probes = []
    # Source torus: radius32 cm plus2.3 cm tyre; wheelbase110 cm,
    # hubs34 cm high. These7.5 cm spheres cover the upper240-degree rim
    # with about1.2 cm outer skin. The bottom120 degrees remain ground contact.
    for wheel, forward in [('front', 55.), ('rear', -55.)]:
        for angle in range(-30, 211, 15):
            rad = math.radians(angle)
            probes.append(dict(id=f'{wheel}_rim_{angle}',
                centre_cm=[round(forward + 28 * math.cos(rad), 7), 0., round(34 + 28 * math.sin(rad), 7)],
                radius_cm=7.5))
    # Source handlebar runs left/right31 cm at forward38/up106 cm.
    # Seven6 cm spheres include both ends and the stem region.
    for index in range(7):
        probes.append(dict(id=f'handlebar_{index}',
            centre_cm=[38., round(-25 + index * 50 / 6, 7), 106.], radius_cm=6.))
    data = dict(schema_version=1, coordinate_contract='bicycle_local_forward_right_up_cm',
        source_path='pipeline/blender/build_kit.py', source_sha256=digest(ROOT/'pipeline/blender/build_kit.py'),
        scope='M1 approximate walking bicycle clearance, centred frame and unsteered front wheel; root rider capsule remains active',
        wheel_source=dict(hub_forward_cm=[-55,55],hub_height_cm=34,torus_major_radius_cm=32,tyre_radius_cm=2.3),
        handlebar_source=dict(forward_cm=38,height_cm=106,half_width_cm=31),
        omitted_contact='Bottom120 degrees of tyres: support traces handle ground contact. This is not full bicycle rigid-body collision.',
        wheel_probe_outer_skin_cm=1.2, minimum_level_probe_bottom_above_frame_base_cm=12.5,
        maximum_rotation_segment_degrees=2., frame_origin_below_actor_cm=70., probes=probes,
        runtime_review='not run', release_accepted=False)
    save_json(ROOT/'manifests/walking-bike-contact.json', data)
    rows = ['// Generated by pipeline/gis/build_walking_bike_contact.py. Units: cm.',
        '// Approximate walking contact only; retain the root capsule and ground support.',
        '#pragma once', '', 'struct FSPWalkingBikeProbe', '{',
        '    double Forward, Right, Up, Radius;', '};', '',
        'inline constexpr FSPWalkingBikeProbe SPWalkingBikeProbes[] =', '{']
    for probe in probes:
        rows.append('    {' + ', '.join(f'{v:.7f}' for v in [*probe['centre_cm'],probe['radius_cm']]) + '}, // ' + probe['id'])
    rows += ['};', '', 'inline constexpr double SPWalkingBikeMaximumRotationStep = 2.;', '']
    (ROOT/'unreal/Source/StanleyParkSim/SPWalkingBikeGeometry.h').write_text('\n'.join(rows), encoding='utf8')
    print(json.dumps(dict(probe_count=len(probes),manifest='manifests/walking-bike-contact.json',application_run=False)))


if __name__ == '__main__':
    main()
