[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=3F4C2AE14020C1239B991585D4E325D1
ProjectName=Stanley Park
Description=Stanley Park Seawall exploration and bicycle ride.
ProjectVersion=0.5.1

[/Script/UnrealEd.ProjectPackagingSettings]
BuildConfiguration=PPBC_Shipping
bUsePakFile=True
bUseIoStore=True
bGenerateChunks=False
bIncludeCrashReporter=False
bCompressed=True
+MapsToCook=(FilePath="/Game/Maps/StanleyParkSeawall")
; Include native character and ambient assets in standalone builds.
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/Seawall/Birds")
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/Explorer")
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/Kit")
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/Audio")
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/Seawall/ParkDetails_v05")
+DirectoriesToAlwaysCook=(Path="/Game/StanleyPark/UI")
+DirectoriesToAlwaysStageAsUFS=(Path="WorldData")
